branch-defaults:
  main:
    environment: null
global:
  application_name: Package
  branch: main
  default_ec2_keyname: n
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: package-detection
  sc: git
  workspace_type: Application
