# Generated by Django 4.1.4 on 2022-12-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="num_packages",
            field=models.IntegerField(default=0),
        ),
    ]
