# Generated by Django 4.1.4 on 2022-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_alert_num_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="num_packages",
            field=models.IntegerField(),
        ),
    ]
