# Generated by Django 4.1.4 on 2022-12-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_alter_alert_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="image",
        ),
    ]
