# Generated by Django 4.1.4 on 2022-12-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_remove_alert_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="alert_images/"),
        ),
    ]
