# Generated by Django 4.1.4 on 2022-12-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0011_package_detection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Package_Detection",
        ),
    ]
